announcement:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

announcementList:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

accountVerification:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

activateMember:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

bankInformation:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

bonusDetails:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

cp3Withdrawal:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

maturityWithdrawal:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

convertCp3ToCp1:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

convertEcashToEpoint:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

cp3Log:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doMemberRegistration:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

downloadMt4:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

downlineList:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doMaturityAction:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

ecashWithdrawal:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

ecashLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

epointLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

epointPurchase:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fetchAnnouncementById:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fetchTopupPackage:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fetchPackage:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fmc:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fundManagementReport:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

fundManagementContract:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

loginPassword:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

maintenanceLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

memberRegistration:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

memberRegistration2:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

mt4Withdrawal:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

packagePurchaseViaBankTransfer:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

packagePurchase:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

packageUpgrade:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

pendingMemberList:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

pinLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

placePlacement:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

purchasePackage:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

purchasePackageViaTree:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

purchasePackageViaTree2:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

placementTree:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

reloadTopup:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

rpLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

rtLog:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

sponsorTree:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

summary:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transactionPassword:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferPin:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferEcash:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferEpoint:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferCp2:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferCp3:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferCp4:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

transferRP:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

convertCp2ToRt:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

convertCp3ToRt:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

upgradePackageViaTree:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

updateBankInformation:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

viewProfile:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

viewBankInformation:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

changeSponsor:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

changeSponsorB:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

all:
  is_secure:  off        # off is the default value anyway